### ISSUE TITLE
Addgif broken for non-admin users

### ISSUE THREAD

**Issue by Sar4h-3** [BlackDemonFire/lukas#394] opened 2023-07-15 17:19 UTC
While testing for #390, I noticed that the function for non-admins to add a gif is broken. 
While you, as an admin can accept the request, nothing happens after.

**Comment by KommentatorForAll** [comment] 2023-07-15 19:04
The cause seems to be missing permissions for direct message reactions.
Though adding it causes the bot to lose connection to the db for some reason

**Comment by KommentatorForAll** [comment] 2023-07-16 16:51
merged in #397

**Closed by KommentatorForAll** 2023-07-16 16:51 UTC
Labels: bug
